### PR TITLE
Add klo-gba.js links

### PR DESCRIPTION
**Pull request by macabeus**
Add two new links:
- for the project [klo-gba.js](https://github.com/macabeus/klo-gba.js)
- for [series of posts](https://medium.com/@bruno.macabeus/reverse-engineering-a-gameboy-advance-game-introduction-ec185bd8e02) about this project

### CODE REVIEW

**Comment by avivace** [comment]
These look interesting and I think they fit the list.
However, they are pretty specifc resources and we gotta find a category like "Related projects" for something "indirect" like this

**Comment by macabeus** [comment]
@avivace Well... since there are so few links on this list, I think that we could put rom hacking stuffs on the categories that we already have. What do you think?
If you prefer, I could update my PR adding this new category, `Related projects` or `Rom hacking`.

**Comment by avivace** [comment]
A new category "Rom Hacking" will problably be better to put your two links

**Comment by macabeus** [comment]
@avivace Done

**Comment by avivace** [comment]
Thank you! I merged the two links and made the thing a bit clearer. Merging now

**Pull request merged**
