### PR TITLE
Fix list of emulators

### PR DESCRIPTION
**Pull request by AntonioND**
The list was clearly wrong.

Also, remove list of emulator development tools. We don't need anyone to develop a better emulator.

### CODE REVIEW

**Comment by AntonioND** [comment]
Also for gbdev: https://github.com/gbdev/awesome-gbdev/pull/214

**Review by avivace — APPROVED** [review]

**Comment by avivace** [comment]
Makes sense, maybe we can add a big H1 header at the top giving VBA the relevance it deserves?

**Comment by AntonioND** [comment]
> Makes sense, maybe we can add a big H1 header at the top giving VBA the relevance it deserves?

To be fair, when this PR is applied, VBA will be the only relevant resource in this list. I'm not sure if it even makes sense to have more entries. But sure, H1 sounds good to me.

**Comment by AntonioND** [comment]
As much as I like this change, the amount of hate mail and threats I've received is too big to justify the merge. I would end up with no cash, and actually using a GB for my day to day work, or maybe a Pentium 1 computer with Windows 98. I'm sorry, but I will need to close this. It's too soon, people are not ready for this change.

**Pull request closed without merging**
