### PR TITLE
Add a link to GBA develop Wiki

### PR DESCRIPTION
**Pull request by laqieer**
It includes many documentations, tutorials and source codes (especially an AVG game engine).

### CODE REVIEW

**Comment by avivace** [comment]
The resource looks really useful, but I think we should keep everything accessible in english (and maybe create a secondary file gathering the non-english stuff).

Is this decent/understandable using a translating service?

**Comment by laqieer** [comment]
It includes complete source code for many gba projects. They are in C instead of Japanese.

**Comment by avivace** [comment]
> It includes complete source code for many gba projects. They are in C instead of Japanese.

Comments in that code are still in Japanese, so I'm still not sure how relevant could it be

**Comment by avivace** [comment]
Add here: https://github.com/gbdev/awesome-gbadev/blob/master/NON_ENG.md

**Pull request closed without merging**
